class AppData {
  static const List<String> majors = [
    'Design & Digital Innovation',
    'Business Administration',
    'Digital Business Management',
    'Intl. Business & Entrepreneurship',
    'Finance',
    'Hospitality & Tourism Management',
    'Risk Management & Insurance',
    'Marketing',
    'Real Estate',
    'Supply Chain Management',
    'Accountancy',
    'Business Economics',
    'Creative Commercial Communication',
    'Imagineer Media Entrepreneurship',
    'Creative Communication Design',
    'Interior Design',
    'Product Design',
    'Lighting Design',
    'Exhibition Design',
    'Fashion Design',
    'Interactive Design',
    'Design Management',
    'Architecture',
    'Interior Architecture',
    'Multi-Disciplinary Design',
    'Business English',
    'Business French',
    'Business Chinese',
    'Business Japanese',
    'English-Chinese Digital Communication',
    'Music Entrepreneurship',
    'Computer Science',
    'Information Technology',
    'Nursing Science',
    'Laws (LL.B.)',
  ];

  static const List<String> years = [
    'Year 1',
    'Year 2',
    'Year 3',
    'Year 4',
    'Year 5+',
    'Graduate',
  ];

  static const List<String> skills = [
    'Flutter',
    'React',
    'Python',
    'Java',
    'JavaScript',
    'TypeScript',
    'Node.js',
    'Swift',
    'Kotlin',
    'C++',
    'Go',
    'Rust',
    'SQL',
    'MongoDB',
    'Firebase',
    'AWS',
    'Docker',
    'Git',
    'UI/UX Design',
    'Machine Learning',
  ];
}
