class AppData {
  static const List<String> majors = [
    'Design & Digital Innovation',
    'Business Administration',
    'Digital Business Management',
    'Intl. Business & Entrepreneurship',
    'Finance',
    'Hospitality & Tourism Management',
    'Risk Management & Insurance',
    'Marketing',
    'Real Estate',
    'Supply Chain Management',
    'Accountancy',
    'Business Economics',
    'Creative Commercial Communication',
    'Imagineer Media Entrepreneurship',
    'Creative Communication Design',
    'Interior Design',
    'Product Design',
    'Lighting Design',
    'Exhibition Design',
    'Fashion Design',
    'Interactive Design',
    'Design Management',
    'Architecture',
    'Interior Architecture',
    'Multi-Disciplinary Design',
    'Business English',
    'Business French',
    'Business Chinese',
    'Business Japanese',
    'English-Chinese Digital Communication',
    'Music Entrepreneurship',
    'Computer Science',
    'Information Technology',
    'Nursing Science',
    'Laws (LL.B.)',
  ];

  static const List<String> years = [
    'Year 1',
    'Year 2',
    'Year 3',
    'Year 4',
    'Year 5+',
    'Graduate',
  ];

  static const Map<String, List<String>> suggestedSkillsByMajor = {
    'Computer Science': ['Python', 'Java', 'JavaScript', 'C++', 'SQL', 'Git', 'Machine Learning', 'Docker', 'Flutter', 'React', 'Node.js', 'AWS'],
    'Information Technology': ['Python', 'SQL', 'JavaScript', 'Git', 'Docker', 'AWS', 'Firebase', 'MongoDB', 'Node.js', 'Networking', 'Cybersecurity'],
    'Design & Digital Innovation': ['UI/UX Design', 'Figma', 'Adobe XD', 'Prototyping', 'Photoshop', 'Illustrator', 'Canva'],
    'Business Administration': ['Excel', 'PowerPoint', 'Project Management', 'Data Analysis', 'Leadership', 'CRM'],
    'Digital Business Management': ['Digital Marketing', 'SEO', 'Data Analysis', 'Excel', 'Google Analytics', 'CRM', 'E-commerce'],
    'Intl. Business & Entrepreneurship': ['Excel', 'Project Management', 'Business Development', 'PowerPoint', 'Leadership', 'Market Research'],
    'Finance': ['Excel', 'Financial Modeling', 'Data Analysis', 'SQL', 'Power BI', 'Bloomberg', 'Python'],
    'Hospitality & Tourism Management': ['Customer Service', 'Event Planning', 'CRM', 'Microsoft Office', 'Communication'],
    'Risk Management & Insurance': ['Excel', 'Data Analysis', 'SQL', 'Risk Assessment', 'Power BI'],
    'Marketing': ['Social Media Marketing', 'SEO', 'Content Creation', 'Google Analytics', 'Canva', 'Copywriting', 'Adobe XD'],
    'Real Estate': ['Excel', 'AutoCAD', 'Market Analysis', 'PowerPoint', 'CRM'],
    'Supply Chain Management': ['Excel', 'SAP', 'Data Analysis', 'Logistics Planning', 'SQL', 'Power BI'],
    'Accountancy': ['Excel', 'QuickBooks', 'Data Analysis', 'SQL', 'Accounting Software', 'Power BI'],
    'Business Economics': ['Excel', 'Data Analysis', 'SQL', 'R', 'Python', 'SPSS', 'Power BI'],
    'Creative Commercial Communication': ['Copywriting', 'Social Media Marketing', 'Content Creation', 'Canva', 'SEO'],
    'Imagineer Media Entrepreneurship': ['Video Editing', 'Photography', 'Social Media Marketing', 'Content Creation', 'Premiere Pro'],
    'Creative Communication Design': ['Photoshop', 'Illustrator', 'After Effects', 'Canva', 'Typography', 'InDesign'],
    'Interior Design': ['AutoCAD', 'SketchUp', 'Revit', '3D Modeling', 'Photoshop', 'Illustrator'],
    'Product Design': ['SolidWorks', 'Fusion 360', '3D Modeling', 'Prototyping', 'Rhino', 'Illustrator'],
    'Lighting Design': ['AutoCAD', 'DIALux', '3D Modeling', 'Revit'],
    'Exhibition Design': ['AutoCAD', 'SketchUp', '3D Modeling', 'Photoshop', 'Illustrator'],
    'Fashion Design': ['Illustration', 'Adobe Illustrator', 'Photoshop', 'Pattern Making', 'Adobe InDesign'],
    'Interactive Design': ['UI/UX Design', 'JavaScript', 'HTML/CSS', 'Prototyping', 'Figma', 'After Effects'],
    'Design Management': ['Project Management', 'UI/UX Design', 'Figma', 'Photoshop', 'Leadership'],
    'Architecture': ['AutoCAD', 'Revit', 'SketchUp', '3D Modeling', 'Rhino', 'Photoshop'],
    'Interior Architecture': ['AutoCAD', 'Revit', 'SketchUp', '3D Modeling', 'Photoshop'],
    'Multi-Disciplinary Design': ['UI/UX Design', 'Figma', '3D Modeling', 'Prototyping', 'Photoshop', 'Illustrator'],
    'Business English': ['Copywriting', 'Content Writing', 'Communication', 'Presentation', 'Translation'],
    'Business French': ['Translation', 'Copywriting', 'Content Writing', 'Communication', 'Presentation'],
    'Business Chinese': ['Translation', 'Copywriting', 'Content Writing', 'Communication', 'Presentation'],
    'Business Japanese': ['Translation', 'Copywriting', 'Content Writing', 'Communication', 'Presentation'],
    'English-Chinese Digital Communication': ['Translation', 'Content Writing', 'Social Media Marketing', 'Copywriting'],
    'Music Entrepreneurship': ['Music Production', 'Audio Engineering', 'Social Media Marketing', 'Content Creation', 'Logic Pro'],
    'Nursing Science': ['Healthcare Research', 'Patient Care', 'Microsoft Office', 'Data Analysis', 'Communication'],
    'Laws (LL.B.)': ['Legal Research', 'Contract Drafting', 'Public Speaking', 'Microsoft Office', 'Excel'],
  };

  static const List<String> skills = [
    'Flutter',
    'React',
    'Python',
    'Java',
    'JavaScript',
    'TypeScript',
    'Node.js',
    'Swift',
    'Kotlin',
    'C++',
    'Go',
    'Rust',
    'SQL',
    'MongoDB',
    'Firebase',
    'AWS',
    'Docker',
    'Git',
    'UI/UX Design',
    'Machine Learning',
  ];
}
